apiVersion: v1
kind: Pod 
metadata:  
  name: test
spec:   
  containers:
    - name: test-container
      image: rapa.iptime.org:5000/nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app: test
  ports:
    - name: test
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
