apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      name: test
      labels:
        app: test
    spec:
      containers:
        - name: nginx
          image: rapa.iptime.org:5000/nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app: test
  ports:
    - name: test
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
